### PR TITLE
Weather re #2: * Now, feedback is a tab. * The settings button is a button now. * You can read individual forecasts items. * Added .gitignore from addontemplate

### PR DESCRIPTION
**Pull request by derekriemer**

### CODE REVIEW

**Comment by derekriemer** [comment]
Whoops, no!

**Comment by derekriemer** [comment]
Okay, well it merges perfectly on my machine here.

**Comment by derekriemer** [comment]
Go ahead

**Comment by josephsl** [comment]
Squash merging. Thanks.

**Pull request closed without merging**
